# Generated by Django 3.2.10 on 2021-12-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlastprices',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='productlastprices',
            name='date',
        ),
    ]
