# Generated by Django 3.2.10 on 2021-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='new_bidder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
