# Generated by Django 3.2.10 on 2021-12-18 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Auction', '0002_auto_20211218_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlastprices',
            name='bidder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_Authentication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlastprices',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
