# Generated by Django 3.2.10 on 2021-12-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auction', '0004_auto_20211218_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
